spring:
  application:
    name: payment-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/payment
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #    database-platform: mysql
  liquibase:
    change-log: classpath:/master/changelog-master.xml

  cloud:
    stream:
      bindings:
        confirmPaymentOrder-out-0:
          destination: confirm-payment-order
          binder: kafka
        failPaymentOrder-out-0:
          destination: fail-payment-order
          binder: kafka

server:
  port: 8090
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

